name: news_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 5.0.7+27

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.3
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.5
  dots_indicator: ^2.1.0
  easy_localization: ^3.0.0
  firebase_auth: ^4.6.1
  firebase_core: ^2.4.1
  firebase_messaging: ^14.6.1
  firebase_storage: ^11.2.1
  flutter_web_browser: ^0.17.0
  flutter_html: ^3.0.0-beta.1
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.1
  html_unescape: ^2.0.0
  image_picker: ^0.8.7+5
  intl: ^0.18.0
  introduction_screen: ^3.1.8
  launch_review: ^3.0.1
  line_icons: ^2.0.1
  lottie: ^2.3.2
  package_info: ^2.0.2
  path_provider: ^2.0.15
  provider: ^6.0.5
  share: ^2.0.4
  shared_preferences: ^2.1.1
  skeleton_text: ^3.0.0
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.11
  youtube_player_flutter: ^8.1.2
  rounded_loading_button: ^2.0.9
  firebase_analytics: ^10.4.1
  flutter_facebook_auth: ^5.0.11
  the_apple_sign_in: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  jiffy: ^5.0.0
  loading_indicator: ^3.1.0
  reading_time: ^2.0.0
  pod_player: ^0.1.4
  google_mobile_ads: ^3.0.0
  # facebook_audience_network: ^1.0.1
  app_settings: ^4.2.0
  csslib: 0.17.2
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  md2_tab_indicator:
    git:
      url: https://github.com/westdabestdb/md2_tab_indicator
      



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.1.0



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"



# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation_files/
    - assets/translations/

  fonts:

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500

    - family: Manrope
      fonts:
        # - asset: assets/fonts/Manrope-Light.ttf
        #   weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900
