name: news_admin
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 5.0.7+19

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cached_network_image: ^3.2.3
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.5
  firebase_core: ^2.13.0
  flutter_html: ^3.0.0-beta.1
  http: ^0.13.6
  intl: ^0.18.1
  line_icons: ^2.0.1
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.11
  google_fonts: ^4.0.4
  html_unescape: ^2.0.0
  firebase_auth: ^4.6.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:

    - family: THICKCCBOI
      fonts:
        - asset: assets/fonts/THICCCBOI-Light.ttf
          weight: 400
        - asset: assets/fonts/THICCCBOI-Regular.ttf
          weight: 500
        - asset: assets/fonts/THICCCBOI-Medium.ttf
          weight: 600
        - asset: assets/fonts/THICCCBOI-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/THICCCBOI-Bold.ttf
          weight: 800

  assets:

    - assets/images/
